version: 2
jobs:
  build:
    docker:
    # use the same docker base as the project
      - image: python:3.7.3-stretch
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt"  }}
      
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.18.0/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      
      - save_cache:
          paths:
          - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt"  }}
      
      # Run lint
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint